### PR TITLE
WIP -- releases/riak 2.1.0

### PR DESCRIPTION
**Pull request by TheOnlyRew**

### CODE REVIEW

**Comment by TheOnlyRew** [comment]
@glickbot commented on 7943384. Still relevant to 2d7d031.

> The verbiage for Zabbix and New Relic look good, though I'd recommend being a little more specific for New Relic and calling it a "hosted service" instead of just a "platform".

**Comment by TheOnlyRew** [comment]
@randysecrist commented on 7943384. Still relevant to 2d7d031.

> ### Under the Community and Open Source Tools

> Anything we can do to soften the language of ‘no support’? We should try to answer the question of what a person should do if they need something changed, updated, etc.

> Could perhaps point them to a community doc thing?

> Questions to answer?

> * If they send a PR what process should they follow?
> * If they don’t have time, patience, or people to make a PR (but something is still not working right and they need something) who should they contact?
>  * Answer: Call Basho Services, but they may need to pay us to make it a priority.

> ### Nagios:

> We should describe at a high level what each of the nagios modules that exist do. The ones we have may be a good fit for what they are looking for and they can dig deeper into the repo.

> If not, they may want to send us others, or have us build more.

> The names of the scripts are pretty descriptive:

> https://github.com/basho/riak_nagios/tree/master/src

**Comment by TheOnlyRew** [comment]
@randysecrist,
Regarding the 'no support' line, I'm having trouble finding the right language to use in replacing it. The tools that note applies to haven't been assigned _dedicated_ Basho support, so they're not being updated with Riak 2.x.x monitoring features. I agree that adding a "If you'd like to help improve these tools, feel free to reach out to Basho's Services department" is a good idea, but these tools aren't even hosted by Basho. Prescribing a process for extending them isn't within the purview of our documentation.
If you have and suggestions for language to use here, I'd love to hear them.

As for the Nagios scripts, I'm completely unfamiliar with how Nagios is deployed, used, or extended. Is there someone more familiar with that tool we can get to write up a few sentences there? I'd be happy to convert an email or a comment to this PR to a commit against the docs, but I'm really not sure how to describe any of these tools.

**Comment by mjbrender** [comment]
Hey @TheOnlyRew - we've been using the phrasing "Community supported" to cover times like these. For example from the template CONTRIBUTING file [here](https://github.com/basho-labs/the-riak-community/blob/master/CONTRIBUTING-basho-labs.md): 

>This repository is community supported. We both appreciate and need your contribution to keep it stable.

cc @randysecrist

**Comment by TheOnlyRew** [comment]
@mjbrender the current line reads
```
Many of the below third-party tools are either general-purpose tools with no
dedicated Riak support, or have plugins that were designed and/or built for a
specific use case in mind.
```

On re-reading it, maybe that line should read "no dedicated Basho support", but it still describes a strange class of projects---maybe community supported, maybe written by Basho, maybe written by one of our clients.

**Comment by mjbrender** [comment]
@TheOnlyRew good point. Here's my go at a re-write: 

```
The below tools were either created by third-parties or Basho engineers for general usage and have been passed to the community for further updates. Like all code under [Basho Labs](https://github.com/basho-labs/), there is no dedicated Basho support and are "best effort." We both appreciate and need your contribution to keep it stable. Please open up a GitHub issue on the repository if you'd like to be a maintainer.
```

Thoughts?

**Comment by TheOnlyRew** [comment]
Yissssssss
I like that a lot more than what I have. Thanks!

**Comment by mjbrender** [comment]
:+1: Glad to help.

**Comment by TheOnlyRew** [comment]
Just so the conversation is complete, the div has been changed to read

```
Many of the below tools were either created by third-parties or Basho engineers
for general usage, and have been passed to the community for further updates. As
such, many of the below only aggregate the statistics and messages that were
output by Riak 1.4.x.</br>
Like all code under [Basho Labs](https://github.com/basho-labs/), there is no
dedicated Basho support and are "best effort." We both appreciate and need your
contribution to keep these tools stable and up to date. Please open up a GitHub
issue on the repository if you'd like to be a maintainer.</br>
Look for banners calling out the tools that do support the full set of Riak 2.x
statistics!
```

**Comment by TheOnlyRew** [comment]
To wrap up the conversation regarding Nagios, it's been decided that the docs aren't the right place to enumerate the available modules. There's been [an issue in riak_nagios](https://github.com/basho/riak_nagios/issues/39) opened up to add an enumeration there, so that updates may easily be made.

**Comment by jhmullen** [comment]
+1

**Pull request merged**
