### PR TITLE
Write-once buckets spelling

### PR DESCRIPTION
**Pull request by lucperkins**
Sorry, this was bugging me

### CODE REVIEW

**Comment by mjbrender** [comment]
May the 4th be with you @lucperkins :+1:

**Comment by laurenrother** [comment]
:candy:

**Comment by lucperkins** [comment]
Capitalizing Riak Data Types is *definitely* not grammatically sound, but it *is* considered a product name by Basho (like Riak Search) and needs to remain capitalized.

**Comment by laurenrother** [comment]
@lucperkins Per Justin, they're a feature rather than a product... hm...

**Pull request merged**
