### PR TITLE
fixing confusing lines from merge

### PR DESCRIPTION
**Pull request by jhmullen**
this addresses issue #1577

### CODE REVIEW

**Comment by TheOnlyRew** [comment]
Lines 119 and 120 should also be removed, I think.

**Comment by kesslerm** [comment]
The warning in lines 119:120 can be folded into the start of the section.

**Comment by TheOnlyRew** [comment]
Step 3 is already "Ensure that Riak is not running on any of the nodes." so the warning is pretty redundant.

**Comment by TheOnlyRew** [comment]
+1

**Pull request merged**
