### PR TITLE
Add a context to all http examples for data types that should have one

### PR DESCRIPTION
**Pull request by russelldb**
Since people tend to cut and paste examples, I think it better to have the recommended `context` field for all operations that should use one (removes, flag disables.) I also shortened the context to resemble one more typically seen in normal operation.

### CODE REVIEW

**Comment by kesslerm** [comment]
Please be consistent with the placement of the colon. The JSON code examples usually have no space before, and one space after the colon (e.g. "context": "value")

**Comment by russelldb** [comment]
@kesslerm did you know you can commit on the actual line in the diff?

**Comment by russelldb** [comment]
Updated

**Comment by laurenrother** [comment]
Hi @russelldb ! I'm happy to merge this if you rebase it. Bonus points if you reissue the PR to target riak/2.1.1, but completely not required.

**Comment by laurenrother** [comment]
These examples look totally different now. Closing this PR and deleting the branch from the repo. If the examples are still wrong in the new Hugo deployment, let me know and we can fix them :)

**Pull request closed without merging**
