### PR TITLE
Update crawler rules

### PR DESCRIPTION
**Pull request by TheOnlyRew**
This change was made in parity with an update to the archived_docs.basho.com.tar.bz2 content. <meta name="robots" content="noindex"> tags were added to all archived content via some perl hacking.

For more details, please see `curl http://s3.amazonaws.com/downloads.basho.com/documentation_content/README | less`

### CODE REVIEW

**Comment by lukebakken** [comment]
So really the important change is in `robots.txt`, right?

**Comment by TheOnlyRew** [comment]
The removal of some no-longer-existent resources from the robots.txt is the most significant change, yes. The change to basho_rake_deploy.rb should not change its functionality at all.

**Comment by lukebakken** [comment]
Makes sense to me, I'm kind of surprised those paths were in `robots.txt` at all :+1:

**Comment by TheOnlyRew** [comment]
well, I put 'em there when we did have old content getting dropped into those paths. But we don't no more!

**Pull request merged**
