### PR TITLE
Fix the issue where h# elements covered preceeding text

### PR DESCRIPTION
**Pull request by TheOnlyRew**

### CODE REVIEW

**Comment by TheOnlyRew** [comment]
Forgot to note in the comment that @angrycub came up with the code to correct the behavior. I just put it in the .scss file.

**Comment by angrycub** [comment]
Tested this PR locally with hugo and this... 
works on my machine

**Comment by laurenrother** [comment]
👍 @TheOnlyRew did you want @erjohnson to look this over before we merge?

**Comment by erjohnson** [comment]
👍

**Pull request merged**
