### PR TITLE
Copy edits for typos

### PR DESCRIPTION
**Pull request by epc**

### CODE REVIEW

**Comment by epc** [comment]
Do you have a contributor's agreement I need to assign/ assign copyright?

**Comment by kesslerm** [comment]
Hi @epc,

Thank you for your contribution, it is very valuable to us.

+1 for the changes.

We currently haven't got a contributor's agreement. All of our open-source code is available under the [Apache License](http://www.apache.org/licenses/LICENSE-2.0), and the documentation is licensed under the [Creative Commons Attribution license](http://creativecommons.org/licenses/by/3.0/). By submitting patches you agree to those patches being integrated into to the repository under the conditions of the repository's license.

Is the license OK for you? We will merge your pull request once we receive a positive answer from you.

Regards,

Magnus

**Comment by epc** [comment]
I am ok with the license.
I recommend adding a CONTRIBUTING or CONTRIBUTING.md — https://github.com/blog/1184-contributing-guidelines

**Comment by kesslerm** [comment]
Thank you for the suggestion. There are already some instructions on how to contribute to the documentation effort in https://github.com/basho/basho_docs/blob/master/README.md#how-to-contribute, but we will try to make this clearer by providing a dedicated document.

Regards,

Magnus

**Comment by epc** [comment]
The benefit of the CONTRIBUTING doc is that github prompts collaborators to read the doc before submitting a pull request (if they detect a CONTRIBUTING or CONTRIBUTING.md doc).  When I was (briefly) at @mongodb/docs we found adding the CONTRIBUTING file almost eliminated the back and forth over assigning copyright (which 10gen/mongodb required even though the docs were CC).

**Pull request merged**
