### PR TITLE
Expand the Riak Metrics to Graph section

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Users frequently ask "So which metrics should I graph?". This is an attempt to expand the Metrics to Graph section and provide some guidance for choosing a "bare minimum" set of stats (from various Professional Services recommendations and training documents).

### CODE REVIEW

**Comment by drewkerrigan** [comment]
+1 3873be9, Much more useful in this format as well. Eventually we should add links to the monitoring plugins after they are polished.

**Comment by TheOnlyRew** [comment]
It looks like this commit is inconsistent about column lengths. I think Luc was pretty strict about a 70-column limit where possible, and -- while the tables shouldn't bother with the limit -- it looks like there's a good bit of prose that should be brought in.

**Comment by dmitrizagidulin** [comment]
@TheOnlyRew thanks! I'll revise to fall under 70-col limit. Can we add that requirement to the README?

**Comment by TheOnlyRew** [comment]
That's a really good idea, actually. I'll try to walk the docs a bit and see if there are any other style guidelines that should be written down.

**Comment by dmitrizagidulin** [comment]
Revised to be under 80-col limit, as per discussion in Docs room.

**Comment by TheOnlyRew** [comment]
+1

**Pull request merged**
