### PR TITLE
Add some typed bucket examples to list buckets and keys

### LINKED ISSUE #2337: HTTP list buckets doesn't give bucket type example [JIRA: DOC-753]
http://docs.basho.com/riak/kv/2.2.0/developing/api/http/list-buckets/

We should add an example of listing buckets in a type.

See this ML thread:

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2016-December/018879.html

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #2337 (DOC-753)

Small improvements to HTTP listing API docs

### CODE REVIEW

**Comment by laurenrother** [comment]
@lukebakken You OK with my " " removal? If so, I'll merge. If not, I'll revert.

**Comment by angrycub** [comment]
I'm +1 on removing the quotes.  I don't know that we call out the default bucket type any place else with quotes.

**Comment by lukebakken** [comment]
At least I didn't call it the legacy type, amirite?

**Pull request merged**
