### PR TITLE
Update MapReduce docs

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes [`DOC-20`](https://bashoeng.atlassian.net/browse/DOC-20)

### CODE REVIEW

**Comment by lukebakken** [comment]
@laurenrother this is ready. I will have a separate PR with the same changes against the [`riak_2.0.8` branch](https://github.com/basho/basho_docs/tree/riak_2.0.8)

**Comment by lukebakken** [comment]
@laurenrother - I don't see any `2.0.8` directories in the `riak_2.0.8` branch so I'm assuming these changes don't need to be back-ported to any previous Riak versions?

**Comment by laurenrother** [comment]
@lukebakken https://github.com/basho/basho_docs/tree/riak_2.0.8/content/riak/kv/2.0.8 ?

**Pull request merged**
